### ISSUE TITLE
Config option to keep the same inventory through all worlds

### ISSUE THREAD

**Issue by theralphy** [silvicky/CombinedWorld#1]
There isn't really any good Multi-world/dimension mod for fabric, this is only one i can find that has the concept of Groups/Worlds/Dimensions.  Its a great mod! But I'd love the option to use the same inventory though out different worlds

**Comment by silvicky** [comment]
let me think howto...i will do it later, after all these things

**Comment by silvicky** [comment]
OH I made it! Thank you for giving advice.
